#ifndef TRX_TRX_MANAGER_DEFAULTS_H
#define TRX_TRX_MANAGER_DEFAULTS_H

#include <stdio.h>

#define DEFAULT_IBME_ID "ibme"
#define DEFAULT_BK_BASENAME "bk.trx"
#define DEFAULT_BK_BASENAME_SIZE 7

#endif //TRX_TRX_MANAGER_DEFAULTS_H
